title: EduWit | mBlock
description: Guías sencillas para aprender robótica y programación con las EduBoards de EduWit.
theme: minima
lang: es-MX
markdown: kramdown

header_pages:
  - EduBoard-UNO/index.md
  - EduBoard-UNO/proyectos.md
  - EduBoard-UNO/ayuda.md
